#!/bin/bash

if [[ "$#" -ne 1 ]]
  then
    echo "Insufficient argument"
    exit
fi

OPS_NODE_SSH=$1

mvn package install -DskipTests

scp target/hadoop-mapreduce-client-app-2.7.1.jar $OPS_NODE_SSH:~/

ssh $OPS_NODE_SSH \
   'mv ~/hadoop-mapreduce-client-app-2.7.1.jar $HADOOP_PREFIX/share/hadoop/mapreduce/;'
