#!/bin/bash

mvn package -Pdist -DskipTests

scp target/hadoop-mapreduce-client-core-2.7.1.jar riza@users.emulab.net:/proj/ucare/riza/

ssh riza@users.emulab.net \
   'mv /proj/ucare/riza/hadoop-mapreduce-client-core-2.7.1.jar $HADOOP_PREFIX/share/hadoop/mapreduce/;'