#!/bin/bash

. cluster_topology.sh

echo "Cleaning up logs" > /tmp/$USER-clcleanup.log

for i in `seq 0 $MAX_NODE`;
do
  echo "$HOSTNAME_PREFIX$i" >> /tmp/$USER-clcleanup.log
  ssh $HOSTNAME_PREFIX$i \
   'rm -rf /tmp/hadoop-ucare/logs* ;'  >> /tmp/$USER-clcleanup.log
done

cat /tmp/$USER-clcleanup.log
