#!/bin/bash

#rm -rf /proj/ucare/riza/datadir > /tmp/clreset.log

echo "Cleaning up logs" > /tmp/clcleanup.log

for i in `seq 0 20`;
do
  echo "node-$i" >> /tmp/clcleanup.log
  ssh node-$i \
   'rm -rf /tmp/hadoop-riza/logs* ;'  >> /tmp/clcleanup.log
done

cat /tmp/clcleanup.log
