#!/bin/bash


echo "Cleaning up logs" > /tmp/$USER-clcleanup.log

for i in `seq 0 20`;
do
  echo "node-$i" >> /tmp/$USER-clcleanup.log
  ssh node-$i \
   'rm -rf /tmp/hadoop-ucare/logs* ;'  >> /tmp/$USER-clcleanup.log
done

cat /tmp/$USER-clcleanup.log
