#!/bin/bash


echo "Resetting cluster" > /tmp/$USER-clreset.log

for i in `seq 0 20`;
do
  echo "node-$i" >> /tmp/$USER-clreset.log
  ssh node-$i \
   'rm -rf /tmp/hadoop-ucare* ; rm -rf /mnt/extra/dfs-ucare ;'  >> /tmp/$USER-clreset.log
done

cat /tmp/$USER-clreset.log
