#!/bin/bash

echo "Resetting cluster" > /tmp/$USER-clresetyarn.log

for i in `seq 0 20`;
do
  echo "node-$i" >> /tmp/$USER-clresetyarn.log
  ssh node-$i \
   'rm -rf /mnt/extra/dfs-ucare/nm-local-dir ;'  >> /tmp/$USER-clresetyarn.log
done

cat /tmp/$USER-clresetyarn.log
