#!/bin/bash

echo "Initial cluster setup" > /tmp/$USER-clsetup.log

for i in `seq 0 20`;
do
  echo "node-$i" >> /tmp/$USER-clsetup.log
  ssh -t node-$i \
   'sudo chown :ucare /mnt/extra; sudo chmod 777 /mnt/extra;'  >> /tmp/$USER-clsetup.log
done

cat /tmp/$USER-clsetup.log
