

MAX_NODE=3
HOSTNAME_PREFIX="node-"

YARN_RM="${HOSTNAME_PREFIX}0"
YARN_RM_IP=10.1.1.2
YARN_RM_HOSTNAME="${HOSTNAME_PREFIX}0"
HDFS_NN="${HOSTNAME_PREFIX}0"
HDFS_NN_IP=10.1.1.2
CLIENT_NODE="${HOSTNAME_PREFIX}0"
SLAVES_FILE="$PSBIN/ucare_se_conf/hadoop-etc/hadoop-2.7.1/slaves"

#SLAVES_FILE=/proj/ucare/git/hadoop-ucare/psbin/mini-slaves

