#!/bin/bash

hdfs dfsadmin -report > /tmp/dfsreport.txt
yarn node -list -states RUNNING > /tmp/yarnreport.txt
grep "^DFS Used:" /tmp/dfsreport.txt > /tmp/dfsused.txt
cat /tmp/dfsused.txt > /tmp/healthreport.txt
cat /tmp/yarnreport.txt >> /tmp/healthreport.txt
#cat /tmp/dfsreport.txt >> /tmp/healthreport.txt
cat /tmp/healthreport.txt
