#!/bin/bash

. cluster_topology.sh

#rm -rf /proj/ucare/riza/datadir > /tmp/clreset.log

echo "Merging logs"

cd /tmp
rm -rf logs

for i in `seq 1 $MAX_NODE`;
do
  echo "$HOSTNAME_PREFIX$i"
  ssh $HOSTNAME_PREFIX$i 'cd /tmp/hadoop-ucare ; tarit logs ;'
  scp $HOSTNAME_PREFIX$i:/tmp/hadoop-ucare/logs.tgz /tmp/
  untarit logs.tgz
  rm logs.tgz
done

cd /tmp/logs/
cp -r $TESTDIR/workGenLogs ./
mv workGenLogs/genstats.py ./
chmod -R 774 . 

#cd yarn/userlogs/
#cp $PSBIN/genstats.py ./
#sed -i "s/^SLOWNODE=.*/SLOWNODE=8/" genstats.py
#sed -i "s/^SLOWHOST=.*/SLOWHOST=\"pc812\"/" genstats.py
